#!/bin/bash

echo "Compiling Files..."

# Compile all Java files, specifying the correct classpath
"C:\Users\loaiw\AppData\Local\Programs\Eclipse Adoptium\jdk-21.0.6.7-hotspot\bin\javac.exe" -cp "libs/gson-2.10.1.jar;." -d bin tool/*.java food/*.java

# Check if compilation was successful
if [ $? -eq 0 ]; then
    echo "Running Program..."
    echo ""

    # Run the Java program with the correct classpath
    "C:\Users\loaiw\AppData\Local\Programs\Eclipse Adoptium\jdk-21.0.6.7-hotspot\bin\java.exe" -cp "libs/gson-2.10.1.jar;bin" food.FoodApp
else
    echo "Compilation failed."
fi

